services:
  mongo:
    image: mongo:7
    container_name: recommendationservic-mongo
    restart: unless-stopped

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}

    ports:
      - "5438:27017"

    volumes:
      - recommendationservic_mongo_data:/data/db

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: recommendationservic-service
    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "1505:1505"

    environment:
      SERVER_PORT: ${SERVER_PORT}
      MONGO_URI: ${MONGO_URI}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_AUTOCONFIGURE_EXCLUDE: ${SPRING_AUTOCONFIGURE_EXCLUDE}
      AI_PROVIDER: ${AI_PROVIDER}
      GROQ_API_KEY: ${GROQ_API_KEY}
      GROQ_MODEL: ${GROQ_MODEL}
      MISTRAL_API_KEY: ${MISTRAL_API_KEY}
      MISTRAL_MODEL: ${MISTRAL_MODEL}
      JWT_SECRET: ${JWT_SECRET}

    depends_on:
      mongo:
        condition: service_healthy

volumes:
  recommendationservic_mongo_data:
